# Generated by Django 5.0.7 on 2024-08-15 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='friends_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
